import { useNavigate } from "react-router-dom";

export default function TermsPage() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#0a0f0d] text-[#f8faf8] font-sans relative flex flex-col justify-between">
      {/* Glow Effects */}
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[400px] h-[400px] bg-green-muted/10 rounded-full blur-[150px] pointer-events-none" />

      {/* Nav */}
      <nav className="flex items-center justify-between px-10 py-6 bg-[#0a0f0d] border-b border-white/5 relative z-10">
        <div className="flex items-center gap-2 cursor-pointer" onClick={() => navigate("/")}>
          <div className="flex h-6 w-6 items-center justify-center rounded-[6px] bg-[#4ade80]">
            <svg
              width="12"
              height="12"
              viewBox="0 0 16 16"
              fill="none"
              stroke="#0a0f0d"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M3 8l3 3 7-7" />
            </svg>
          </div>
          <span className="text-md font-semibold tracking-tight text-[#f8faf8]">
            PrepAI
          </span>
        </div>
        <button
          onClick={() => navigate("/")}
          className="text-xs font-semibold px-4 py-2 rounded-lg border border-white/10 text-muted hover:text-[#f8faf8] hover:border-white/20 transition-all cursor-pointer"
        >
          Back to Home
        </button>
      </nav>

      {/* Content */}
      <main className="flex-1 max-w-3xl w-full mx-auto px-6 py-16 relative z-10">
        <div className="bg-surface border border-white/5 rounded-2xl p-8 md:p-10 shadow-2xl relative">
          <div className="mb-8 border-b border-white/5 pb-6">
            <span className="text-[10px] font-bold tracking-widest text-green uppercase font-mono">
              legal terms
            </span>
            <h1 className="text-3xl font-extrabold tracking-tight mt-1 text-[#f8faf8]">
              Terms & Conditions
            </h1>
            <p className="text-xs text-muted mt-2 font-mono">
              Last updated: June 8, 2026
            </p>
          </div>

          <div className="space-y-6 text-xs text-muted leading-relaxed font-sans">
            <section>
              <h3 className="text-sm font-bold text-[#f8faf8] mb-2 font-mono">1. Agreement to Terms</h3>
              <p>
                By accessing or using PrepAI, you agree to be bound by these Terms & Conditions. If you disagree with any part of these terms, you may not access the service.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[#f8faf8] mb-2 font-mono">2. User Accounts</h3>
              <p>
                To utilize the interview practice dashboard, you must authenticate through our secure Auth0 provider. You are responsible for maintaining the confidentiality of your account credentials and represent that all information provided is accurate and current.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[#f8faf8] mb-2 font-mono">3. Session Credits & Billing</h3>
              <p>
                PrepAI operates on a credits-based pricing model:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1.5">
                <li>New registrants receive 3 free practice credits.</li>
                <li>Additional credits can be purchased in packages (3 sessions for ₹29, 5 sessions for ₹49, 10 sessions for ₹75).</li>
                <li>All payments are processed securely through the Razorpay gateway. You agree to pay the fees displayed at checkout.</li>
              </ul>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[#f8faf8] mb-2 font-mono">4. Permissible Use</h3>
              <p>
                You agree not to abuse the AI interview platform, including attempts to bypass credit checks, scrape interview questions, submit malicious audio inputs, or disrupt the operation of our cloud servers. Any violation will lead to immediate account termination without refund.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[#f8faf8] mb-2 font-mono">5. Limitation of Liability</h3>
              <p>
                PrepAI is designed for practices and learning simulations. We make no guarantees regarding actual employment placement or success in live interviews based on the feedback scorecards generated by our algorithms.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[#f8faf8] mb-2 font-mono">6. Governing Law</h3>
              <p>
                These terms shall be governed by and construed in accordance with the laws of India, and any disputes relating to these terms shall be subject to the exclusive jurisdiction of the courts of Bhubaneswar, Odisha.
              </p>
            </section>
          </div>
        </div>
      </main>

      {/* Compact footer */}
      <footer className="py-6 border-t border-white/5 text-center text-[10px] text-dim font-mono relative z-10">
        PrepAI • Secured Sandbox Compliance • All rights reserved
      </footer>
    </div>
  );
}
